In [1]:
import torch

In [2]:
tensor = torch.tensor(
    [[2,2],[3,3],[4,4]], dtype=torch.float32, requires_grad=True
)

In [3]:
tensor

tensor([[2., 2.],
        [3., 3.],
        [4., 4.]], requires_grad=True)

In [4]:
tensor_0=torch.zeros([2,3,4],dtype=torch.int32)
tensor_0

tensor([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]], dtype=torch.int32)

In [6]:
tensor_like = torch.full_like(tensor_0, 5, dtype=torch.float32, requires_grad=True)
tensor_like

tensor([[[5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.]],

        [[5., 5., 5., 5.],
         [5., 5., 5., 5.],
         [5., 5., 5., 5.]]], requires_grad=True)

In [7]:
torch.arange(2,10,2)

tensor([2, 4, 6, 8])

In [33]:
tensor = torch.tensor([1,2,3,4])
tensor.view([2,2])

tensor([[1, 2],
        [3, 4]])

In [ ]:
tensor = torch.tensor([1,2,3,4])
tensor = torch.unsqueeze(tensor, 0)
# tensor.view([1,1])
tensor

tensor([[1, 2, 3, 4]])

In [44]:
print(torch.cpu.is_available())

True


In [52]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
tensor = torch.tensor([1,2,3,4], dtype=torch.float32, requires_grad=True)
tensor = tensor.to(device)
print(tensor.device)
print(tensor)

cpu
tensor([1., 2., 3., 4.], requires_grad=True)


In [53]:
new_tensor = tensor.detach()
new_tensor

tensor([1., 2., 3., 4.])

In [57]:
tensor[3].item()

4.0

In [60]:
tensor.dtype

torch.float32

In [69]:
tensor = torch.tensor([[0.9203, 0.0898, 0.0234, 0.7694],
        [0.4938, 0.8529, 0.3978, 0.5617]])
tensor

tensor([[0.9203, 0.0898, 0.0234, 0.7694],
        [0.4938, 0.8529, 0.3978, 0.5617]])

In [71]:
tensor.view(4,2,1)

tensor([[[0.9203],
         [0.0898]],

        [[0.0234],
         [0.7694]],

        [[0.4938],
         [0.8529]],

        [[0.3978],
         [0.5617]]])

In [83]:
torch.manual_seed(42)
tensor = torch.randint(0, 10, size=[3, 2, 4], dtype=torch.int64)
tensor

tensor([[[2, 7, 6, 4],
         [6, 5, 0, 4]],

        [[0, 3, 8, 4],
         [0, 4, 1, 2]],

        [[5, 5, 7, 6],
         [9, 6, 3, 1]]])

In [94]:
new_tensor = torch.unsqueeze(tensor, 2)
new_tensor

tensor([[[[2, 7, 6, 4]],

         [[6, 5, 0, 4]]],


        [[[0, 3, 8, 4]],

         [[0, 4, 1, 2]]],


        [[[5, 5, 7, 6]],

         [[9, 6, 3, 1]]]])