In [1]:
import torch

In [4]:
tensor_001 = torch.tensor([[1,1],[2,2]])
tensor_002 = torch.tensor([[3,3],[4,4]])
tensor_cat = torch.cat([tensor_001,tensor_002])

In [5]:
tensor_001

tensor([[1, 1],
        [2, 2]])

In [6]:
tensor_002

tensor([[3, 3],
        [4, 4]])

In [7]:
tensor_cat

tensor([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [11]:
tensor_001 = torch.tensor([[1,1],[2,2]])
tensor_002 = torch.tensor([[3,3],[4,4]])
tensor_cat = torch.cat([tensor_001,tensor_002], dim=1)

In [20]:
tensor_001.shape

torch.Size([2, 2])

In [9]:
tensor_cat

tensor([[1, 1, 3, 3],
        [2, 2, 4, 4]])

In [15]:
tensor_001 = torch.tensor([[1,3],[2,2]])
tensor_002 = torch.tensor([[3,3],[2,2]])
tensor_equal = tensor_001 == tensor_002
tensor_all = torch.all(tensor_equal)

print(tensor_001)
print(tensor_002)
print(tensor_equal)
print(tensor_all)


tensor([[1, 3],
        [2, 2]])
tensor([[3, 3],
        [2, 2]])
tensor([[False,  True],
        [ True,  True]])
tensor(False)


In [18]:
tensor_001 = torch.tensor([[1,3],[2,2]])
tensor_002 = torch.tensor([[3,3],[2,2]])
tensor_equal = tensor_001 == tensor_002
tensor_all = torch.all(tensor_equal, dim=0)

print(tensor_001)
print(tensor_002)
print(tensor_equal)
print(tensor_all)

tensor([[1, 3],
        [2, 2]])
tensor([[3, 3],
        [2, 2]])
tensor([[False,  True],
        [ True,  True]])
tensor([False,  True])


### Practice

In [19]:
torch.add(tensor_001, tensor_002)

tensor([[4, 6],
        [4, 4]])